In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("BostonHousing.csv")
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [3]:
display(df.shape)
df.dropna()
display(df.shape)

(506, 14)

(506, 14)

In [4]:
X = df.drop(columns = ["medv"])
display(X)

y = df['medv']
display(y)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(X_train)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
477,15.02340,0.0,18.10,0,0.6140,5.304,97.3,2.1007,24,666,20.2,349.48,24.91
15,0.62739,0.0,8.14,0,0.5380,5.834,56.5,4.4986,4,307,21.0,395.62,8.47
332,0.03466,35.0,6.06,0,0.4379,6.031,23.3,6.6407,1,304,16.9,362.25,7.83
423,7.05042,0.0,18.10,0,0.6140,6.103,85.1,2.0218,24,666,20.2,2.52,23.29
19,0.72580,0.0,8.14,0,0.5380,5.727,69.5,3.7965,4,307,21.0,390.95,11.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.17120,0.0,8.56,0,0.5200,5.836,91.9,2.2110,5,384,20.9,395.67,18.66
270,0.29916,20.0,6.96,0,0.4640,5.856,42.1,4.4290,3,223,18.6,388.65,13.00
348,0.01501,80.0,2.01,0,0.4350,6.635,29.7,8.3440,4,280,17.0,390.94,5.99
435,11.16040,0.0,18.10,0,0.7400,6.629,94.6,2.1247,24,666,20.2,109.85,23.27
102,0.22876,0.0,8.56,0,0.5200,6.405,85.4,2.7147,5,384,20.9,70.80,10.63

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(13,)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

E:\Avdhoot\GitHub\AG1713\Practicals\LP3\ML\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [8]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [9]:
model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16
)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 558.2649 - mae: 21.6218
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 443.6098 - mae: 18.8316
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 277.2730 - mae: 14.2337
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 129.3532 - mae: 8.9325
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 66.3180 - mae: 6.2185
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 39.2999 - mae: 4.7346
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6864 - mae: 3.8901
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.3040 - mae: 3.5226
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.2571 - mae: 3.3213
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.0553 - mae: 3.1993
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.7494 - mae: 3.0786
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.9139 - mae: 3.0145
Epoch 13/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.0844 - mae: 2.9122
Epoch 14/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.5885 - mae: 2.8787
Epoch 15/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.9483 - mae: 2.8112
Epoch 16/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.4754 - mae: 2.7973
Epoch 17/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14.8849 - mae: 2.7114
Epoch 18/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14.5136 - mae: 2.7037
Epoch 19/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.0961 - mae: 2.6492
Epoch 20/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.7751 - mae: 2.6360
Epoch 21/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4221 - mae: 2.5766
Epoch 22/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.4570 - mae: 2.6080
Epoch 23/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9499 - mae: 2.5606
Epoch 24/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.8514 - mae: 2.5314
Epoch 25/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.3939 - mae: 2.4941
Epoch 26/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.2224 - mae: 2.4776
Epoch 27/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.3382 - mae: 2.4799
Epoch 28/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9505 - mae: 2.4578
Epoch 29/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.7839 - mae: 2.4132
Epoch 30/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6041 - mae: 2.4388
Epoch 31/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.5030 - mae: 2.4063
Epoch 32/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1139 - mae: 2.3702
Epoch 33/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1047 - mae: 2.3860
Epoch 34/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9309 - mae: 2.3437
Epoch 35/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.7434 - mae: 2.3226
Epoch 36/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.6073 - mae: 2.3416
Epoch 37/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.6898 - mae: 2.3481
Epoch 38/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3467 - mae: 2.2983
Epoch 39/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.1619 - mae: 2.2959
Epoch 40/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.1959 - mae: 2.2906
Epoch 41/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0714 - mae: 2.2668
Epoch 42/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.7754 - mae: 2.2407
Epoch 43/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8169 - mae: 2.2633
Epoch 44/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.7101 - mae: 2.2278
Epoch 45/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.5941 - mae: 2.2240
Epoch 46/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.5418 - mae: 2.2020
Epoch 47/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4544 - mae: 2.2092
Epoch 48/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.7219 - mae: 2.2170
Epoch 49/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4193 - mae: 2.2385
Epoch 50/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0755 - mae: 2.1885
Epoch 51/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9032 - mae: 2.1592
Epoch 52/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9752 - mae: 2.1905
Epoch 53/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.7482 - mae: 2.1594
Epoch 54/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.7668 - mae: 2.1532
Epoch 55/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5505 - mae: 2.1077
Epoch 56/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.7286 - mae: 2.1693
Epoch 57/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6003 - mae: 2.1376
Epoch 58/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5800 - mae: 2.1393
Epoch 59/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.3907 - mae: 2.1181
Epoch 60/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5184 - mae: 2.0988
Epoch 61/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3851 - mae: 2.1442
Epoch 62/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0131 - mae: 2.0573
Epoch 63/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.8779 - mae: 2.0601
Epoch 64/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.8015 - mae: 2.0442
Epoch 65/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.7393 - mae: 2.0529
Epoch 66/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6981 - mae: 2.0260
Epoch 67/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.7593 - mae: 2.0595
Epoch 68/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5922 - mae: 2.0370
Epoch 69/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6152 - mae: 2.0375
Epoch 70/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.5617 - mae: 2.0377
Epoch 71/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7205 - mae: 2.0304
Epoch 72/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4610 - mae: 2.0058
Epoch 73/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.4153 - mae: 1.9839
Epoch 74/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.3174 - mae: 2.0133
Epoch 75/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7474 - mae: 2.0566
Epoch 76/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.1078 - mae: 1.9802
Epoch 77/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9692 - mae: 1.9667
Epoch 78/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9472 - mae: 1.9657
Epoch 79/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.8741 - mae: 1.9500
Epoch 80/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.9421 - mae: 1.9615
Epoch 81/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.8013 - mae: 1.9383
Epoch 82/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7595 - mae: 1.9435
Epoch 83/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.6445 - mae: 1.9564
Epoch 84/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7658 - mae: 1.9472
Epoch 85/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5832 - mae: 1.9031
Epoch 86/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4557 - mae: 1.9015
Epoch 87/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5069 - mae: 1.9064
Epoch 88/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5554 - mae: 1.8915
Epoch 89/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3012 - mae: 1.8758
Epoch 90/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5354 - mae: 1.9157
Epoch 91/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5192 - mae: 1.8879
Epoch 92/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.3550 - mae: 1.8798
Epoch 93/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2677 - mae: 1.8881
Epoch 94/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2717 - mae: 1.8620
Epoch 95/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2670 - mae: 1.8409
Epoch 96/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9512 - mae: 1.8159
Epoch 97/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9946 - mae: 1.8275
Epoch 98/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.0297 - mae: 1.8345
Epoch 99/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.0117 - mae: 1.8233
Epoch 100/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9090 - mae: 1.7964

In [10]:
y_pred = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

In [11]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Square: ",r2)

MSE: 11.671167449105154
R2 Square:  0.8408486928379306

In [12]:
loss, mae = model.evaluate(X_test, y_test)
print (mae)

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 11.6712 - mae: 2.2405
2.240480422973633